### ISSUE TITLE
add: support for threading

### ISSUE THREAD

**Issue by metaist** [metaist/ezq#1]
The relevant API for `Thread` is the same as `Process`.

**Comment by metaist** [comment]
This seems pretty easy to do.

```python
from threading import Thread

def run_thread(func: Callable[..., Any], *args: Any, **kwargs: Any) -> Thread:
    """Run a function as a thread.

    Args:
        func (Callable): function to run in each thread
        *args (Any): additional positional arguments to `func`.
        **kwargs (Any): additional keyword arguments to `func`.

    Returns:
        Thread: thread that was started
    """
    worker = Thread(daemon=True, target=func, args=args, kwargs=kwargs)
    worker.start()
    return worker
```

And literally everything else stays the same.

**Comment by metaist** [comment]
Ah, but if you don't want the `pickle` constraint, you need to use a different kind of queue. Hm. What should I call this kind of `Queue`? Maybe `BasicQueue`.

```python
from queue import Queue as BasicQueue
```

**Comment by metaist** [comment]
Updating the `README` is going to be painful. Almost everything 

- [x] Why this library?
- [x] When should I use threads vs processes?
- [x] An example that uses processes and threads.
- [x] When do I need to worry about `pickle`? (processes)
- [x] When do I need to worry about variable scope? (threads)
- [x] When can workers create more workers?

**Comment by metaist** [comment]
For the example, I'm thinking I take a bunch of words and split them across processes and each process creates a bunch of threads with everything piping back to the same output queue.

**Comment by metaist** [comment]
@pugio made a good point that I should look into `async`/`await` vs `Thread`.
Going to read: https://itnext.io/practical-guide-to-async-threading-multiprocessing-958e57d7bbb8

**Comment by metaist** [comment]
Another @pugio point: What's the actual use-case for adding anything beyond `multiprocessing`?
I guess a use-case I sometimes have is scraping websites: I want to use all the CPUs and because everything is waiting for the network, I want several threads per CPU.

**Comment by metaist** [comment]
Here's a little fake example of using multiple process-based workers each of which has multiple thread-based workers.

```python
#!/usr/bin/env python
"""Example of using a mixture of processes and threads."""

# pkg
import ezq


def worker_thread(q, out):
    for msg in ezq.iter_msg(q):
        ezq.put_msg(out, data=ord(msg.data))


def worker_process(q, out):
    q2 = ezq.BasicQueue()  # this can be a thread-friendly queue
    threads = [ezq.run_thread(worker_thread, q2, out) for _ in range(10)]
    for msg in ezq.iter_msg(q):
        for letter in msg.data:
            ezq.put_msg(q2, data=letter)
    ezq.endq_and_wait(q2, threads)


def main():
    # both queues need to be multiprocessor-friendly
    q, out = ezq.Queue(), ezq.Queue()
    workers = [ezq.run(worker_process, q, out) for _ in range(ezq.NUM_CPUS)]

    data = """
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam in semper
        tortor, ac maximus magna. Sed quis rhoncus nulla. Vestibulum at felis dolor.
        Morbi quis odio ut lorem molestie viverra sed nec augue. Pellentesque
        vestibulum sollicitudin euismod. Vivamus ullamcorper justo at erat hendrerit,
        vitae blandit erat imperdiet. Proin faucibus nisl non sem finibus tristique.
        Nunc scelerisque, felis ac consequat auctor, ligula orci placerat dui, sed
        ultricies risus ligula convallis risus. Cras volutpat ipsum neque, nec finibus
        lacus interdum vitae. Aliquam erat volutpat.
    """
    for word in data.split(" "):
        ezq.put_msg(q, data=word)
    ezq.endq_and_wait(q, workers)

    print(sum(msg.data for msg in ezq.iter_q(out)))


if __name__ == "__main__":
    main()
```

**Comment by Pugio** [comment]
So `.run()` and `.run_thread`, but the essential usage patterns are the same. I like this.

**Comment by metaist** [comment]
Almost done with this, but battling with `mypy` over type-narrowing. Turns out that it can only [narrow the type](https://docs.python.org/3/library/typing.html#typing.TypeGuard) if you do an `isinstance` check with a single class.

```python
# works
if isinstance(workers, Thread):
    _workers = [workers]
elif isinstance(workers, Process):
    _workers = [workers]
else:
    _workers = workers

# doesn't work
if isinstance(workers, (Thread, Process)):
    _workers = [workers]
else:
    _workers = workers

# also doesn't work
if isinstance(workers, Thread) or isinstance(workers, Process):
    _workers = [workers]
else:
    _workers = workers
```

That's kinda annoying.

**Comment by metaist** [comment]
I'm suddenly experiencing threads that are hanging on the `.join` call. Oh no.

**Comment by metaist** [comment]
After much exploration, I have finally realized it's because I followed `pylint` obnoxious `keyword-arg-before-vararg` rule when I shouldn't have.
